spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5532/user_service_db
    username: user_service
    password: user_service
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/liquibase-master.yaml
    enabled: false
  main:
    allow-bean-definition-overriding: true